Add onlineDevice to active reader if it not active
Change-Id: I9b7243787dff0a56a7995592585ef9cade92455c

diff --git a/tools/share/zvmguestconfigure b/tools/share/zvmguestconfigure
--- a/tools/share/zvmguestconfigure
+++ b/tools/share/zvmguestconfigure
@@ -37,6 +37,32 @@
 version=3.0
 authorizedSenders=''
 
+function onlineDevice {
+  # @Description:
+  #   Brings a Linux device online.
+  # @Input:
+  #   Device number, e.g. "0.0.000c"
+  # @Output:
+  #   Return code indicates success or failure
+  # @Code:
+  device=$1
+  local funcName="onlineDevice"
+  rc=$(/sbin/chccwdev -e $device > /dev/null; echo $?)
+  if (( rc != 0 )); then
+    if [[ -e /sbin/cio_ignore ]]; then
+      rc=$(/sbin/cio_ignore -r 0.0.$device > /dev/null; echo $?)
+      which udevadm &> /dev/null && udevadm settle || udevsettle
+    fi
+    rc=$(/sbin/chccwdev -e $device > /dev/null; echo $?)
+    if (( rc != 0 )); then
+      echo "zvmguestconfigure $funcName (Error) Could not activate the virtual device $device"
+      return 1
+    fi
+  fi
+  which udevadm &> /dev/null && udevadm settle || udevsettle
+  return 0
+}
+
 function pullReader {
   # @Description:
   #   Reads class x spool files from the reader if sent by an authorized sender.
@@ -113,13 +139,6 @@ function pullReader {
       /bin/tar xf $file -C $transportdir
       rm $file
       /bin/bash invokeScript.sh
-    elif [[ $type == "disk" ]]; then
-      echo 'disk file encountered and will be handled by the deprecated setupDisk function'
-      rc=$(/usr/sbin/vmur re $spoolid $file)
-      if (( rc == 0 )); then
-        setupDisk $transportdir'/'$file
-        rc=0
-      fi
     else
       # Receive block
       rc=$(/usr/sbin/vmur re $spoolid $file)
