fix problem of unit_add/unit_remove in rhel7 scripts
Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

diff --git a/zvmsdk/volumeops/templates/rhel7_attach_volume.j2 b/zvmsdk/volumeops/templates/rhel7_attach_volume.j2
--- a/zvmsdk/volumeops/templates/rhel7_attach_volume.j2
+++ b/zvmsdk/volumeops/templates/rhel7_attach_volume.j2
@@ -1,10 +1,11 @@
 #!/bin/bash
 # Generated by jinja2 template
 fcp_list="{{ fcp_list }}"
+input_wwpns="{{ wwpns }}"
 lun="{{ lun }}"
 target_filename="{{ target_filename }}"
 
-echo "Enter RHEL7 attach script with parameters: FCP list:${fcp_list[@]}, LUN:$lun, target_filename:$target_filename"
+echo "Enter RHEL7 attach script with parameters: FCP list:${fcp_list[@]}, INPUT WWPNS:${input_wwpns[@]}, LUN:$lun, target_filename:$target_filename"
 
 # because jinja2's problem, we can not use # to count the array_size
 fcp_count=0
@@ -48,11 +49,48 @@ done
 
 # the number WWPNs is generated dynamically
 # so we need to get them from the filesystem
-declare -a ActiveWWPNs
-FoundDiskPath=0
+# the number WWPNs is generated dynamically
+# so we need to get them from the filesystem
+# and get the intersection between input wwpns and lszfcp output
+lszfcp_output=`lszfcp -P | awk '{print $1}' | awk -F'/' '{print $1,$2}'`
+echo "lszfcp -P output port info: $lszfcp_output ."
+declare -A valid_dict
 for fcp in ${fcp_list[@]}
 do
-    ActiveWWPNs=(`ls /sys/bus/ccw/drivers/zfcp/0.0.$fcp/ | grep "0x"`)
+    for wwpn in ${input_wwpns[@]}
+    do
+        fcp_wwpn_str="0.0.${fcp} ${wwpn}"
+        if [[ $lszfcp_output =~ $fcp_wwpn_str ]]; then
+            # add this combination into valid_dict
+            if [[ -z ${valid_dict[$fcp]} ]]; then
+                valid_dict+=([$fcp]="$wwpn")
+            else
+                old_value=${valid_dict[$fcp]}
+                new_value=${old_value}" "$wwpn
+                valid_dict[$fcp]=$new_value
+            fi
+        fi
+    done
+done
+echo "Got valid wwpns, list of key is: ${!valid_dict[@]}, list of value is: ${valid_dict[@]} ."
+
+# check the content of valid_dict, if no content, return error
+valid_fcp_count=0
+for fcp in ${!valid_dict[@]}
+do
+    valid_fcp_count=$((valid_fcp_count+=1))
+done
+if [[ $valid_fcp_count -eq 0 ]]; then
+    echo "valid_dict is empty, exit with code 2."
+    exit 2
+fi
+
+# flag which indicate whether we found a valid and accessable path for the volume
+FoundDiskPath=0
+# wait for the device ready
+for fcp in ${!valid_dict[@]}
+do
+    ActiveWWPNs=(${valid_dict[$fcp]})
     echo "Got WWPNs: ${ActiveWWPNs[@]} for FCP device: $fcp"
 
     # If auto-discovery of Fibre-Channel target ports is
@@ -63,16 +101,12 @@ do
         echo 1 > /sys/bus/ccw/drivers/zfcp/0.0.$fcp/port_rescan
     fi
 
-    # If auto-discovery of LUNs is disabled on s390 platforms
-    # luns need to be added to the configuration through
-    # the unit_add interface
-    AutoLunScan=`cat /sys/module/zfcp/parameters/allow_lun_scan`
-    if [[ "$AutoLunScan" != "Y" ]]; then
-        for wwpn in ${ActiveWWPNs[@]}
-        do
-            echo "$lun" > /sys/bus/ccw/drivers/zfcp/0.0.$fcp/$wwpn/unit_add
-        done
-    fi
+    # luns need to be added to the configuration through the unit_add interface
+    # execute this anytime because unit_remove in detach script will fails if no corresponding unit_add
+    for wwpn in ${ActiveWWPNs[@]}
+    do
+        echo "$lun" > /sys/bus/ccw/drivers/zfcp/0.0.$fcp/$wwpn/unit_add
+    done
     
     for wwpn in ${ActiveWWPNs[@]}
     do
@@ -98,8 +132,6 @@ do
             break
         fi
 
-        ActiveWWPNs=(`ls /sys/bus/ccw/drivers/zfcp/0.0.$fcp/ | grep "0x"`)
-        echo "Got WWPNs: ${ActiveWWPNs[@]} for FCP device: $fcp before try disk path."
         # loop all the WWPNs to found the alive device
         for j in ${ActiveWWPNs[@]}
         do
