make error message more clear for punch attach detach script
Attach script exit code explanation:
1: failed because multipathd service is not active
2: failed because input parameters may have problems
3: failed because can not found intersection between input WWPNs and lszfcp output
4: failed because no disk file found in the target VM, means no volume shown in the target VM

Detach script exit code explanation:
1: failed because multipathd service is not active
3: failed because can not found intersection between input WWPNs and lszfcp output
4: failed because no disk file found in the target VM, means no volume shown in the target VM
5: failed to flush a multipath device map

Signed-off-by: CaoBiao <bjcb@cn.ibm.com>

diff --git a/zvmsdk/volumeops/templates/ubuntu_detach_volume.j2 b/zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
--- a/zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
+++ b/zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
@@ -1,5 +1,6 @@
 #!/bin/bash
 # Generated by jinja2 template
+
 fcp_list="{{ fcp_list }}"
 input_wwpns="{{ wwpns }}"
 # lun example: 0x0100000000000000
@@ -17,6 +18,18 @@ lun_id="{{ lun_id }}"
 target_filename="{{ target_filename }}"
 is_last_volume="{{ is_last_volume }}"
 
+# Detach script exit code explanation:
+# OK(0): success
+OK=0
+# MULTIPATH_SERVICE_NOT_ACTIVE(1): failed because multipathd service is not active
+MULTIPATH_SERVICE_NOT_ACTIVE=1
+# INVALID_WWPNS(3): failed because can not found intersection between input WWPNs and lszfcp output
+INVALID_WWPNS=3
+# DEVICE_PATH_NOT_FOUND(4): failed because no disk file found in the target VM, means no volume shown in the target VM
+DEVICE_PATH_NOT_FOUND=4
+# CAN_NOT_FLUSH_MULTIPATH_DEVICE_MAP(5): failed to flush a multipath device map
+CAN_NOT_FLUSH_MULTIPATH_DEVICE_MAP=5
+
 echo "Enter UBUNTU detach script with parameters: FCP:${fcp_list[@]}, INPUT WWPNS:${input_wwpns[@]}, LUN:$lun, LUN ID: $lun_id, target_filename:$target_filename, is_last_volume: $is_last_volume."
 
 # ensure multipathd service is up
@@ -24,8 +37,8 @@ echo "Checking status of multipathd service ..."
 check_multipathd_service=`systemctl is-active --quiet multipathd`
 exit_code=$?
 if [[ $exit_code != 0 ]]; then
-    echo "Detach script terminated because multipathd service is not active!"
-    exit $exit_code
+    echo "Detach script terminated because multipathd service is not active, exit with code 1."
+    exit $MULTIPATH_SERVICE_NOT_ACTIVE
 fi
 
 # Print info of each FCP
@@ -78,8 +91,8 @@ do
     valid_fcp_count=$((valid_fcp_count+=1))
 done
 if [[ $valid_fcp_count -eq 0 ]]; then
-    echo "Can not found intersection between input wwpns: ${input_wwpns[@]} and lszfcp output: $lszfcp_output"
-    exit 3
+    echo "Can not find the intersection between input wwpns: ${input_wwpns[@]} and lszfcp output: $lszfcp_output, exit with code 3."
+    exit $INVALID_WWPNS
 fi
 
 # flag which indicate whether we found a valid and accessable path for the volume
@@ -112,8 +125,8 @@ do
 done
 # if no disk path found, exit with code 4
 if [[ -z $diskPath ]]; then
-    echo "No valid paths found between FCP devices: ${fcp_list[@]} and WWPNS: ${input_wwpns}"
-    exit 4
+    echo "No valid paths found between FCP devices: ${fcp_list[@]} and WWPNS: ${input_wwpns}, exit with code 4."
+    exit $DEVICE_PATH_NOT_FOUND
 fi
 
 # get the wwid of device, the WWID are same for same volume
@@ -126,7 +139,7 @@ blockdev --flushbufs $diskPath > /dev/null
 echo "Flush cache data on $diskPath was done"
 
 # exit code default to 0, because WWID may be empty
-exit_code=0
+exit_code=$OK
 
 # get the map name of the WWID
 # then use multipath -f <map name> to flush the device
@@ -141,13 +154,13 @@ exit_code=$?
 if [ "$output" ]; then
     if [ "$(echo $output | grep -i 'must provide a map name')" ]; then
         echo "ignore error on WWID $WWID and Lun $lun:$output"
-        exit_code=0
+        exit_code=$OK
     elif [ "$(echo $output | grep -i 'in use')" ]; then
         echo "Warning:device $map_name with WWID $WWID and Lun $lun is use, the detachment will continue."
-        exit_code=0
+        exit_code=$OK
     else
-        echo "unknown error on device with WWID $WWID and Lun $lun:$output"
-        exit_code=2
+        echo "Error:when flushing a multipath device map on device with WWID $WWID and Lun $lun failed because:$output"
+        exit_code=$CAN_NOT_FLUSH_MULTIPATH_DEVICE_MAP
     fi
 fi
 echo "Flushing a multipath device map $map_name exit with code: $exit_code"
@@ -192,5 +205,5 @@ udevadm trigger --sysname-match=dm-*
 echo "Undev rules reload done"
 
 echo "Exit RHEL8 detach script"
-exit 0
+exit $OK
 
